title: Delotha I.T. Consulting
description: One Sysadmin's Life

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

show_links: true

# GitHub Pages settings
repository: delotha/delotha.github.io